version: '3.7'

services:
  db:
    container_name: psql
    image: postgres
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/pg_data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/pg_data
    ports:
      - '5432:5432'
  back-docker-node:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    ports:
      - 8080:8080
    depends_on:
      - db